#!/usr/bin/env python3
"""ramen_cve — public façade.

Threat-intel triage on a ramen budget. The implementation now lives in
focused submodules (constants, models, cache, extract, decay, analyze,
associations, keyring, enrich/*, output/*, dispatch/*, config, cliutil,
pipeline, wizard, hunt, pir, trend, audit, schedule, cli). This module
is a pure re-export façade: it preserves the flat
``from ramen_cve import X`` / ``ramen_cve.X`` contract that tests and
users depend on, with zero behaviour change. See README.md and src/ramen_cve/__init__.py.
"""

from __future__ import annotations

import logging
import sys
import time  # noqa: F401  # monkeypatch seam: tests patch ramen_cve.time.sleep

import requests  # noqa: F401  # monkeypatch seam: tests patch ramen_cve.requests.get

from .analyze import (  # noqa: F401
    CWE_TO_KILL_CHAIN,
    KILL_CHAIN_PHASES,
    _admiralty_score,
    _best_admiralty,
    _normalize_tlp,
    _worst_tlp,
    bucket_and_suggest,
    filter_by_date,
    map_cwes_to_attack_techniques,
    map_cwes_to_kill_chain,
)
from .associations import (  # noqa: F401
    _build_actor,
    _build_campaign,
    _build_malware,
    _parse_kev_due_date,
    load_associations,
)
from .audit import (  # noqa: F401
    _AUDIT_SENSITIVE_KEYS,
    _audit_actor,
    _audit_dispatch,
    _redact_audit_args,
    _run_audit,
)
from .bucket_policy import (  # noqa: F401
    BUCKET_IDS,
    DEFAULT_BUCKET_POLICY,
    KEV_BUCKET_ID,
    BucketPolicy,
    BucketSpec,
)
from .cache import Cache  # noqa: F401
from .cli import (  # noqa: F401
    VERSION,
    _configure_logging,
    _dedupe_iocs,
    _run_cve,
    _run_opml,
    _run_stix,
    _run_url,
    _run_web,
    _shared_flags,
    _validate_args,
    build_parser,
    main,
)
from .cliutil import (  # noqa: F401
    _collect_opml_files,
    _parse_iso_date,
    _path_arg,
    _resolve_out_dir,
    _strip_path_quotes,
    _validate_cve_id,
    _validate_opml_input,
)
from .config import (  # noqa: F401
    _YAML_FLAT_KEY_MAP,
    _coerce_yaml_value,
    _load_remembered_opml,
    _reset_remembered_opml,
    _resolve_config_path,
    _save_remembered_opml,
    apply_yaml_config,
    args_to_yaml_payload,
    delete_yaml_preset,
    list_yaml_presets,
    load_yaml_config,
    save_yaml_config,
)

# Constants moved to the Layer-0 `constants` leaf; re-exported so
# `from ramen_cve import X` / `ramen_cve.X` keep working (facade).
from .constants import (  # noqa: F401
    _DEFANG_DETECT,
    _DEFANG_MAP,
    _FILE_EXT_TLDS,
    ATTACK_TECHNIQUE_NAMES,
    BUCKET_ACTIONS,
    CISA_KEV_URL,
    CVE_REGEX,
    CWE_TO_ATTACK,
    DEFAULT_ASSOCIATIONS_PATH,
    DEFAULT_CACHE_PATH,
    DEFAULT_CACHE_TTL_HOURS,
    DEFAULT_CONFIG_DIR,
    DEFAULT_CONFIG_TEMPLATE,
    DEFAULT_CVSS_THRESHOLD,
    DEFAULT_DATA_DIR,
    DEFAULT_EPSS_THRESHOLD,
    DEFAULT_HUNT_DIR,
    DEFAULT_LAST_OPML_PATH,
    DEFAULT_PIR_DIR,
    DEFAULT_PRESETS_DIR,
    DOMAIN_REGEX,
    EMAIL_REGEX,
    EPSS_API_BASE,
    EXPLOIT_STATUS_VALUES,
    EXPLOITDB_CSV_URL,
    GITHUB_SEARCH_URL,
    HUNT_STATUSES,
    IPV4_REGEX,
    MD5_REGEX,
    NUCLEI_TEMPLATES_TREE_URL,
    NVD_API_BASE,
    PIR_STATUSES,
    SHA1_REGEX,
    SHA256_REGEX,
    TLP_LEVELS,
    URL_REGEX,
    USER_AGENT,
)
from .daemon import (  # noqa: F401
    _build_iteration_argv,
    _run_daemon,
)
from .decay import (  # noqa: F401
    IOC_HALF_LIFE_DAYS,
    _ioc_confidence,
    apply_ioc_decay,
    filter_iocs_by_confidence,
)
from .deltas import compute_bucket_deltas  # noqa: F401
from .dispatch.digest import (  # noqa: F401
    _build_digest_body,
    _group_records_by_owner,
    _maybe_digest,
)
from .dispatch.runner import dispatch_records  # noqa: F401
from .dispatch.sinks import (  # noqa: F401
    DISPATCH_DEFAULT_BUCKETS,
    EmailDispatcher,
    GenericWebhookDispatcher,
    SlackWebhookDispatcher,
    _build_default_dispatchers,
    _DispatcherBase,
)
from .enrich.epss import fetch_epss  # noqa: F401
from .enrich.exploits import (  # noqa: F401
    enrich_with_exploit_status,
    fetch_exploitdb_cve_set,
    fetch_nuclei_cve_set,
    search_github_for_cve,
)
from .enrich.inventory import (  # noqa: F401
    _cpe_matches_inventory,
    correlate_inventory,
    load_inventory,
)
from .enrich.iocs import (  # noqa: F401
    ABUSEIPDB_API_BASE,
    MALWAREBAZAAR_API,
    OTX_API_BASE,
    VIRUSTOTAL_API_BASE,
    AbuseIPDBEnricher,
    MalwareBazaarEnricher,
    OtxEnricher,
    VirusTotalEnricher,
    _build_default_enrichers,
    _EnricherBase,
    enrich_iocs,
)
from .enrich.kev import fetch_kev_catalog  # noqa: F401
from .enrich.nvd import (  # noqa: F401
    _empty_nvd,
    _parse_nvd_response,
    fetch_nvd,
)
from .enrich.orchestrator import enrich_cves  # noqa: F401
from .extract import (  # noqa: F401
    _defang_text,
    _is_likely_filename,
    _is_public_ip,
    extract_cves,
    extract_iocs,
    parse_opml,
)
from .hunt import (  # noqa: F401
    _hunt_path,
    _run_hunt,
    load_all_hunts,
    load_hunt,
    save_hunt,
)
from .keyring import (  # noqa: F401
    ENV_FILE_PATH,
    NVD_API_KEY_REGEX,
    NVD_KEY_REQUEST_URL,
    _is_interactive,
    _prompt_for_api_key,
    _redact_key,
    _safe_url_for_log,
    _save_api_key_to_env,
)
from .models import (  # noqa: F401
    Campaign,
    CveRecord,
    EnrichedCve,
    FeedEntry,
    Hunt,
    IocRecord,
    Malware,
    OpmlError,
    Pir,
    ThreatActor,
    WebUiError,
    _utcnow,
)
from .output.csv_writer import (  # noqa: F401
    CSV_COLUMNS,
    EPSS_TRAJECTORY_COLUMNS,
    write_csv,
    write_epss_trajectory_csv,
)
from .output.html_quadrant import (  # noqa: F401
    BUCKET_COLOURS,
    _render_quadrant_svg,
    write_quadrant_html,
)
from .output.markdown import (  # noqa: F401
    BUCKET_DISPLAY,
    BUCKET_ORDER,
    IOC_TYPE_DISPLAY,
    IOC_TYPE_ORDER,
    _md_safe,
    _summarize_enrichment,
    write_markdown,
)
from .output.navigator import (  # noqa: F401
    build_navigator_layer,
    write_navigator,
)
from .output.siem_queries import (  # noqa: F401
    SIEM_QUERY_ELIGIBLE_BUCKETS,
    SIEM_QUERY_PLATFORMS,
    write_siem_query_stubs,
)
from .output.sigma import (  # noqa: F401
    SIGMA_ELIGIBLE_BUCKETS,
    _build_sigma_stub,
    _sigma_level_for,
    _sigma_yaml_escape,
    write_sigma_stubs,
)
from .output.stix import (  # noqa: F401
    _STIX_PATTERN_RE,
    IOC_CSV_COLUMNS,
    _extract_cve_id_from_vuln,
    _extract_iocs_from_pattern,
    _ioc_to_stix_pattern,
    _stix_objects_to_records,
    _stix_uuid,
    parse_stix_bundle,
    pull_taxii,
    write_iocs_csv,
    write_stix,
)
from .output.yara import (  # noqa: F401
    YARA_ELIGIBLE_BUCKETS,
    _build_yara_stub,
    _yara_safe_name,
    _yara_string_escape,
    write_yara_stubs,
)
from .pipeline import (  # noqa: F401
    _KNOWN_OUTPUT_EXTENSIONS,
    _decay_and_filter_iocs,
    _get_github_token,
    _maybe_correlate_inventory,
    _maybe_dispatch,
    _maybe_enrich_iocs,
    _maybe_filter_by_sector,
    _output,
    _resolve_associations,
    _safe_basename,
    _unique_output_path,
)
from .pir import (  # noqa: F401
    _pir_path,
    _run_pir,
    load_all_pirs,
    load_pir,
    save_pir,
)
from .risk import (  # noqa: F401
    CRITICALITY_TIERS,
    apply_risk_scores,
    compute_risk_score,
    worst_criticality,
)
from .schedule import (  # noqa: F401
    _build_schedule_command,
    _emit_cron_line,
    _emit_windows_task_xml,
    _entry_script_path,
    _parse_schedule_time,
    _quote_for_task_scheduler,
    _run_schedule,
)
from .ssvc import (  # noqa: F401
    EXPLOITATION_VALUES,
    EXPOSURE_VALUES,
    HUMAN_IMPACT_VALUES,
    SSVC_ACTIONS,
    UTILITY_VALUES,
    apply_ssvc,
    compute_ssvc,
    normalize_profile,
)
from .trend import (  # noqa: F401
    _SPARKLINE_CHARS,
    _record_runs,
    _run_trend,
    _sparkline,
)
from .web.builder import (  # noqa: F401
    WEB_DEFAULT_MAX_RUNS_ON_HOME,
    build_site,
)
from .wizard import (  # noqa: F401
    _run_wizard,
    _wizard_validate_cve_list,
    _wizard_validate_date,
    _wizard_validate_float,
)

# Locked public surface (plan §7.5). Generated from the re-export
# blocks above; mirrors tests/test_facade.py's contract list.
__all__ = [
    "ABUSEIPDB_API_BASE",
    "ATTACK_TECHNIQUE_NAMES",
    "AbuseIPDBEnricher",
    "BUCKET_ACTIONS",
    "BUCKET_DISPLAY",
    "BUCKET_IDS",
    "BUCKET_ORDER",
    "BucketPolicy",
    "BucketSpec",
    "CISA_KEV_URL",
    "CSV_COLUMNS",
    "CVE_REGEX",
    "CWE_TO_ATTACK",
    "CWE_TO_KILL_CHAIN",
    "Cache",
    "Campaign",
    "CveRecord",
    "DEFAULT_ASSOCIATIONS_PATH",
    "DEFAULT_BUCKET_POLICY",
    "DEFAULT_CACHE_PATH",
    "DEFAULT_CACHE_TTL_HOURS",
    "DEFAULT_CONFIG_DIR",
    "DEFAULT_CONFIG_TEMPLATE",
    "DEFAULT_CVSS_THRESHOLD",
    "DEFAULT_DATA_DIR",
    "DEFAULT_EPSS_THRESHOLD",
    "DEFAULT_HUNT_DIR",
    "DEFAULT_LAST_OPML_PATH",
    "DEFAULT_PIR_DIR",
    "DEFAULT_PRESETS_DIR",
    "DISPATCH_DEFAULT_BUCKETS",
    "DOMAIN_REGEX",
    "EMAIL_REGEX",
    "ENV_FILE_PATH",
    "EPSS_API_BASE",
    "EPSS_TRAJECTORY_COLUMNS",
    "EXPLOITDB_CSV_URL",
    "EXPLOIT_STATUS_VALUES",
    "EmailDispatcher",
    "EnrichedCve",
    "FeedEntry",
    "GITHUB_SEARCH_URL",
    "GenericWebhookDispatcher",
    "HUNT_STATUSES",
    "Hunt",
    "IOC_CSV_COLUMNS",
    "IOC_HALF_LIFE_DAYS",
    "IOC_TYPE_DISPLAY",
    "IOC_TYPE_ORDER",
    "IPV4_REGEX",
    "IocRecord",
    "KEV_BUCKET_ID",
    "KILL_CHAIN_PHASES",
    "MALWAREBAZAAR_API",
    "MD5_REGEX",
    "Malware",
    "MalwareBazaarEnricher",
    "NUCLEI_TEMPLATES_TREE_URL",
    "NVD_API_BASE",
    "NVD_API_KEY_REGEX",
    "NVD_KEY_REQUEST_URL",
    "OTX_API_BASE",
    "OpmlError",
    "OtxEnricher",
    "PIR_STATUSES",
    "Pir",
    "SHA1_REGEX",
    "SHA256_REGEX",
    "SIGMA_ELIGIBLE_BUCKETS",
    "SlackWebhookDispatcher",
    "TLP_LEVELS",
    "ThreatActor",
    "URL_REGEX",
    "USER_AGENT",
    "VERSION",
    "VIRUSTOTAL_API_BASE",
    "VirusTotalEnricher",
    "WEB_DEFAULT_MAX_RUNS_ON_HOME",
    "WebUiError",
    "YARA_ELIGIBLE_BUCKETS",
    "_AUDIT_SENSITIVE_KEYS",
    "_DEFANG_DETECT",
    "_DEFANG_MAP",
    "_DispatcherBase",
    "_EnricherBase",
    "_FILE_EXT_TLDS",
    "_KNOWN_OUTPUT_EXTENSIONS",
    "_SPARKLINE_CHARS",
    "_STIX_PATTERN_RE",
    "_YAML_FLAT_KEY_MAP",
    "_admiralty_score",
    "_audit_actor",
    "_audit_dispatch",
    "_best_admiralty",
    "_build_actor",
    "_build_campaign",
    "_build_default_dispatchers",
    "_build_default_enrichers",
    "_build_digest_body",
    "_build_iteration_argv",
    "_build_malware",
    "_build_schedule_command",
    "_build_sigma_stub",
    "_build_yara_stub",
    "_coerce_yaml_value",
    "_collect_opml_files",
    "_configure_logging",
    "_cpe_matches_inventory",
    "_decay_and_filter_iocs",
    "_dedupe_iocs",
    "_defang_text",
    "_emit_cron_line",
    "_emit_windows_task_xml",
    "_empty_nvd",
    "_entry_script_path",
    "_extract_cve_id_from_vuln",
    "_extract_iocs_from_pattern",
    "_get_github_token",
    "_group_records_by_owner",
    "_hunt_path",
    "_ioc_confidence",
    "_ioc_to_stix_pattern",
    "_is_interactive",
    "_is_likely_filename",
    "_is_public_ip",
    "_load_remembered_opml",
    "_maybe_correlate_inventory",
    "_maybe_digest",
    "_maybe_dispatch",
    "_maybe_enrich_iocs",
    "_maybe_filter_by_sector",
    "_md_safe",
    "_normalize_tlp",
    "_output",
    "_parse_iso_date",
    "_parse_kev_due_date",
    "_parse_nvd_response",
    "_parse_schedule_time",
    "_path_arg",
    "_pir_path",
    "_prompt_for_api_key",
    "_quote_for_task_scheduler",
    "_record_runs",
    "_redact_audit_args",
    "_redact_key",
    "_reset_remembered_opml",
    "_resolve_associations",
    "_resolve_config_path",
    "_resolve_out_dir",
    "_run_audit",
    "_run_cve",
    "_run_daemon",
    "_run_hunt",
    "_run_opml",
    "_run_pir",
    "_run_schedule",
    "_run_stix",
    "_run_trend",
    "_run_url",
    "_run_web",
    "_run_wizard",
    "_safe_basename",
    "_safe_url_for_log",
    "_save_api_key_to_env",
    "_save_remembered_opml",
    "_shared_flags",
    "_sigma_level_for",
    "_sigma_yaml_escape",
    "_sparkline",
    "_stix_objects_to_records",
    "_stix_uuid",
    "_strip_path_quotes",
    "_summarize_enrichment",
    "_unique_output_path",
    "_utcnow",
    "_validate_args",
    "_validate_cve_id",
    "_validate_opml_input",
    "_wizard_validate_cve_list",
    "_wizard_validate_date",
    "_wizard_validate_float",
    "_worst_tlp",
    "_yara_safe_name",
    "_yara_string_escape",
    "apply_ioc_decay",
    "apply_yaml_config",
    "args_to_yaml_payload",
    "bucket_and_suggest",
    "build_parser",
    "build_site",
    "compute_bucket_deltas",
    "correlate_inventory",
    "delete_yaml_preset",
    "dispatch_records",
    "enrich_cves",
    "enrich_iocs",
    "enrich_with_exploit_status",
    "extract_cves",
    "extract_iocs",
    "fetch_epss",
    "fetch_exploitdb_cve_set",
    "fetch_kev_catalog",
    "fetch_nuclei_cve_set",
    "fetch_nvd",
    "filter_by_date",
    "filter_iocs_by_confidence",
    "list_yaml_presets",
    "load_all_hunts",
    "load_all_pirs",
    "load_associations",
    "load_hunt",
    "load_inventory",
    "load_pir",
    "load_yaml_config",
    "main",
    "map_cwes_to_attack_techniques",
    "map_cwes_to_kill_chain",
    "parse_opml",
    "parse_stix_bundle",
    "pull_taxii",
    "requests",
    "save_hunt",
    "save_pir",
    "save_yaml_config",
    "search_github_for_cve",
    "time",
    "write_csv",
    "write_epss_trajectory_csv",
    "write_iocs_csv",
    "write_markdown",
    "write_navigator",
    "build_navigator_layer",
    "write_quadrant_html",
    "write_sigma_stubs",
    "write_stix",
    "write_yara_stubs",
    # SSVC
    "EXPLOITATION_VALUES",
    "EXPOSURE_VALUES",
    "HUMAN_IMPACT_VALUES",
    "SSVC_ACTIONS",
    "UTILITY_VALUES",
    "apply_ssvc",
    "compute_ssvc",
    "normalize_profile",
    # Risk-weighted prioritization
    "CRITICALITY_TIERS",
    "apply_risk_scores",
    "compute_risk_score",
    "worst_criticality",
    # Native SIEM query stubs
    "SIEM_QUERY_ELIGIBLE_BUCKETS",
    "SIEM_QUERY_PLATFORMS",
    "write_siem_query_stubs",
]

_log = logging.getLogger(__name__)


if __name__ == "__main__":
    sys.exit(main())
